version: '3.8'

services:
  web:
    build: .
    image: minimart:dev
    container_name: nextjs
    ports:
      - "80:3000"
    restart: always
    links:
      - db
  db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017